### ISSUE TITLE
Could you please add change comments to osm changesets? 

### ISSUE THREAD

**Issue by sebastian-philipp** [Luzifer/gpxhydrant#1]
For example "Add or modified fire hydrants". Basically, anything would be better than no comment at all. See for example this changset: https://www.openstreetmap.org/changeset/49692863#map=16/53.5880/9.6930

**Comment by Luzifer** [comment]
I can try to re-add the comment… It was removed in https://github.com/Luzifer/gpxhydrant/commit/be0704451ac0280831585db256905250c445e940#diff-7ddfb3e035b42cd70649cc33393fe32cR130 because of the OSM API reacting with non HTTP200 when it was supplied.

**Comment by Luzifer** [comment]
Changeset comments are written again starting with `v0.3.0`: [Changeset #39 on `tomh`](https://tomh.apis.dev.openstreetmap.org/changeset/39)
